/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssetsCategory: typeof import('./src/components/AssetsCategory.vue')['default']
    BarEchart: typeof import('./src/components/page-echart/src/BarEchart.vue')['default']
    BaseEchart: typeof import('./src/components/page-echart/src/BaseEchart.vue')['default']
    BaseTable: typeof import('./src/components/page-table/BaseTable.vue')['default']
    DialogDemo: typeof import('./src/components/page-Dialog/DialogDemo.vue')['default']
    DialogTitle: typeof import('./src/components/DialogTitle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    EmptyBox: typeof import('./src/components/page-others/EmptyBox.vue')['default']
    FloorBigMap: typeof import('./src/components/page-echart/src/FloorBigMap.vue')['default']
    FloorMap: typeof import('./src/components/page-echart/src/FloorMap.vue')['default']
    GaButton: typeof import('./src/components/page-button/Ga-Button.vue')['default']
    GaForm: typeof import('./src/components/page-form/Ga-Form.vue')['default']
    GaSearch: typeof import('./src/components/page-search/Ga-search.vue')['default']
    GaTable: typeof import('./src/components/page-table/Ga-Table.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    LineEchart: typeof import('./src/components/page-echart/src/LineEchart.vue')['default']
    LiquidEchart: typeof import('./src/components/page-echart/src/LiquidEchart.vue')['default']
    LiquidG2: typeof import('./src/components/page-echart/src/LiquidG2.vue')['default']
    MapEchart: typeof import('./src/components/page-echart/src/MapEchart.vue')['default']
    MonthSelect: typeof import('./src/components/page-others/MonthSelect.vue')['default']
    PanelBox: typeof import('./src/components/PanelBox.vue')['default']
    PieEchart: typeof import('./src/components/page-echart/src/PieEchart.vue')['default']
    RangeSelect: typeof import('./src/components/page-others/RangeSelect.vue')['default']
    RingProgress: typeof import('./src/components/page-echart/src/RingProgress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectOption: typeof import('./src/components/SelectOption.vue')['default']
    ToolTip: typeof import('./src/components/page-others/ToolTip.vue')['default']
    VideoPlayer: typeof import('./src/components/VideoPlayer.vue')['default']
    YearSelect: typeof import('./src/components/page-others/YearSelect.vue')['default']
  }
}
